/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spkdesi.view;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import spkdesi.models.ModelProses;

/**
 *
 * @author 6P52
 */
public class FrmProses extends javax.swing.JInternalFrame {

    DefaultTableModel model = new DefaultTableModel() {
        public boolean isCellEditable(int rowIndex, int collIndex) {
            return false;
        }
    };
    DefaultTableModel model1 = new DefaultTableModel() {
        public boolean isCellEditable(int rowIndex, int collIndex) {
            return false;
        }
    };
    DefaultTableModel model2 = new DefaultTableModel() {
        public boolean isCellEditable(int rowIndex, int collIndex) {
            return false;
        }
    };

    /**
     * Creates new form FrmAnalisa
     */
    public FrmProses() {
        initComponents();
        tblDataLampau.setModel(model);
        model.addColumn("Periode");
        model.addColumn("Jumlah Pakai");
        tblBarang();
        loadTblBarang();
    }

    public void tblBarang() {
        tblBarang.setModel(model1);
        model1.addColumn("Kode Barang");
        model1.addColumn("Jenis");
        model1.addColumn("Ukuran");
        model1.addColumn("Stok");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrmBarang = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblBarang = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnLihat = new javax.swing.JButton();
        txtKd = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        periodeAwal = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        periodeAkhir = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDataLampau = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        btnBatal = new usu.widget.ButtonGlass();
        btnSimpan = new usu.widget.ButtonGlass();
        btnHitung = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtHasil = new javax.swing.JTextArea();

        jPanel6.setBackground(new java.awt.Color(255, 78, 9));
        jPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 4, 0, new java.awt.Color(0, 0, 0)));

        jLabel10.setFont(new java.awt.Font("Lucida Calligraphy", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Data Barang");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(229, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBarangMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblBarang);

        javax.swing.GroupLayout FrmBarangLayout = new javax.swing.GroupLayout(FrmBarang.getContentPane());
        FrmBarang.getContentPane().setLayout(FrmBarangLayout);
        FrmBarangLayout.setHorizontalGroup(
            FrmBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(FrmBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        FrmBarangLayout.setVerticalGroup(
            FrmBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrmBarangLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addContainerGap())
        );

        setClosable(true);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 4, 0, new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Lucida Calligraphy", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Form Proses Hitung");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        jLabel5.setText("Kode Barang");

        btnLihat.setText("Lihat Data Lampau");
        btnLihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLihatActionPerformed(evt);
            }
        });

        txtKd.setEditable(false);
        txtKd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        periodeAwal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                periodeAwalPropertyChange(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        jLabel9.setText("Periode Awal");

        jLabel11.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        jLabel11.setText("Periode Akhir");

        periodeAkhir.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                periodeAkhirPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtKd, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(periodeAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(periodeAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(btnLihat)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtKd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnLihat, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(periodeAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(periodeAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 1, 1)), "Tabel Data Lampau", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tblDataLampau.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDataLampau);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(204, 255, 255));

        btnBatal.setText("Batal");
        btnBatal.setEnabled(false);
        btnBatal.setFont(new java.awt.Font("Lucida Calligraphy", 0, 11)); // NOI18N
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.setEnabled(false);
        btnSimpan.setFont(new java.awt.Font("Lucida Calligraphy", 0, 11)); // NOI18N
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnHitung.setText("Hitung Peramalan");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHitung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        txtHasil.setEditable(false);
        txtHasil.setColumns(20);
        txtHasil.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtHasil.setLineWrap(true);
        txtHasil.setRows(5);
        txtHasil.setTabSize(1);
        txtHasil.setMargin(new java.awt.Insets(2, 4, 2, 2));
        jScrollPane2.setViewportView(txtHasil);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String dari, sampai;

    public String autoNumber() {
        ModelProses mk = new ModelProses();
        String number = mk.getId();
        if (number.equals("")) {
            number = "F001";
        } else {
            number = number.substring(2);
            int angka = Integer.parseInt(number);
            angka++;
            if (angka < 10) {
                number = "00" + angka;
            } else if (angka >= 10 && angka < 100) {
                number = "0" + angka;
            } else if (angka >= 100 && angka < 1000) {
                number = "" + angka;
            } else {
                number = String.valueOf(angka);
            }
            if (number.length() > 5) {
                number = number.substring(number.length() - 5, number.length());
            }
            number = "F" + number;
        }
        return number;
    }

    ArrayList<Float> mini = new ArrayList<Float>();
    Map<Float, Double> map = new HashMap<Float, Double>();

    public void mse() {
        for (int b = 0; b < 9; b++) {
            ArrayList xt = new ArrayList();
            ArrayList ft = new ArrayList();
            ArrayList xt_ft = new ArrayList();
            ArrayList xt_ft2 = new ArrayList();
            double alpa[] = {0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9};
            float mse = 0;
            String awal = (String) tblDataLampau.getValueAt(0, 1);
            ft.add(awal);
            for (int a = 0; a < tblDataLampau.getRowCount(); a++) {
                String nilai = (String) tblDataLampau.getValueAt(a, 1);
                xt.add(nilai);
                //hitung pemulusan
                ft.add(alpa[b] * Float.valueOf(xt.get(a).toString()) + (1 - alpa[b]) * Float.valueOf(ft.get(a).toString()));
                //hitung mse
                xt_ft.add(Float.valueOf(xt.get(a).toString()) - Float.valueOf(ft.get(a).toString()));
                xt_ft2.add(Math.round(Math.pow(Float.valueOf(xt_ft.get(a).toString()), 2)));
                mse = mse + Integer.valueOf(xt_ft2.get(a).toString());
            }
            float hasil_mse = mse / xt_ft2.size();
            map.put(hasil_mse, alpa[b]);
            mini.add(hasil_mse);

            xt.clear();
            ft.clear();
            xt_ft.clear();
            xt_ft2.clear();
            mse = 0;
        }
    }

    String id = autoNumber();
    String barang, satuan;
    String tampilan = "";
    Double alpha;
    double hasil;
    float hasil_mse;

    public void hitung() {
        tampilan = "";
        ArrayList xt = new ArrayList();
        ArrayList ft = new ArrayList();
        ArrayList xt_ft = new ArrayList();
        ArrayList xt_ft2 = new ArrayList();
        float mse = 0;
        String awal = (String) tblDataLampau.getValueAt(0, 1);
        float mse_kecil = Collections.min(mini);
        alpha = map.get(mse_kecil);
        ft.add(awal);
        for (int a = 0; a < tblDataLampau.getRowCount(); a++) {
            String nilai = (String) tblDataLampau.getValueAt(a, 1);
            xt.add(nilai);
            //hitung pemulusan
            ft.add(alpha * Float.valueOf(xt.get(a).toString()) + (1 - alpha) * Float.valueOf(ft.get(a).toString()));
            //hitung mse
            xt_ft.add(Float.valueOf(xt.get(a).toString()) - Float.valueOf(ft.get(a).toString()));
            xt_ft2.add(Math.round(Math.pow(Float.valueOf(xt_ft.get(a).toString()), 2)));
            mse = mse + Integer.valueOf(xt_ft2.get(a).toString());
        }
        //hasil ramalan
        int row = tblDataLampau.getRowCount() - 1;
        hasil = (alpha * Float.valueOf(xt.get(row).toString()) + (1 - alpha) * Float.valueOf(ft.get(row).toString()));
        hasil_mse = mse / xt_ft2.size();

        tampilan += "\n";
        tampilan += "\tBerdasarkan perhitungan Metode Single Exponential smoothing untuk jenis barang " + barang + "\n";
        tampilan += "\tdengan satuan " + satuan + " diprediksi periode berikutnya membutuhkan sebanyak " + Math.round(hasil) + ".\n";
        tampilan += "\n";
        tampilan += "\tKeterangan :\n";
        tampilan += "\tHasil Peramalan            = " + Math.round(hasil) + "\n";
        tampilan += "\tAlphadengan Error Terkecil = " + alpha + "\n";
        tampilan += "\tMean Squared Error (MSE)   = " + hasil_mse + "\n";
        txtHasil.setText(tampilan);
        btnBatal.setEnabled(true);
        btnSimpan.setEnabled(true);
    }

    public void loadTblBarang() {
        ModelProses m = new ModelProses();
        ResultSet r = m.read();
        try {
            model1.getDataVector().removeAllElements();
            while (r.next()) {
                Object obj[] = new Object[4];
                obj[0] = r.getString("kd_persediaan");
                obj[1] = r.getString("nama_kategori");
                obj[2] = r.getString("satuan");
                obj[3] = r.getString("stok");
                model1.addRow(obj);
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrmProses.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void btnLihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatActionPerformed
        // TODO add your handling code here:
        ModelProses m = new ModelProses();
        try {
            model.getDataVector().removeAllElements();
            ResultSet t = m.read_data_lampau(txtKd.getText(), dari, sampai);
            while (t.next()) {
                Object obj[] = new Object[2];
                String[] period = t.getString("periode").split("/");
                String periode = "";
                if (period[0].equals("1")) {
                    periode = "Januari";
                } else if (period[0].equals("2")) {
                    periode = "Februari";
                } else if (period[0].equals("3")) {
                    periode = "Maret";
                } else if (period[0].equals("4")) {
                    periode = "April";
                } else if (period[0].equals("5")) {
                    periode = "Mei";
                } else if (period[0].equals("6")) {
                    periode = "Juni";
                } else if (period[0].equals("7")) {
                    periode = "Juli";
                } else if (period[0].equals("8")) {
                    periode = "Agustus";
                } else if (period[0].equals("9")) {
                    periode = "September";
                } else if (period[0].equals("10")) {
                    periode = "Oktober";
                } else if (period[0].equals("11")) {
                    periode = "November";
                } else {
                    periode = "Desember";
                }
                obj[1] = t.getString("jumlah_bulanan");
                obj[0] = periode + "-" + period[1];
                model.addRow(obj);
                //noTable();
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrmProses.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLihatActionPerformed
    public void noTable() {
        int baris = model.getRowCount();
        for (int a = 0; a < baris; a++) {
            String nomor = String.valueOf(a + 1);
            model.setValueAt(nomor, a, 0);
        }
    }

    private void tblBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBarangMouseClicked
        // TODO add your handling code here:
        int i = tblBarang.getSelectedRow();
        String kode = (String) tblBarang.getValueAt(i, 0);
        barang = (String) tblBarang.getValueAt(i, 1);
        satuan = (String) tblBarang.getValueAt(i, 2);
        txtKd.setText(kode);
        FrmBarang.setVisible(false);
    }//GEN-LAST:event_tblBarangMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FrmBarang.setBounds(300, 300, 472, 350);
        FrmBarang.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
        model2.getDataVector().removeAllElements();
        mse();
        hitung();
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Batalkan");
        model.getDataVector().removeAllElements();
        model2.getDataVector().removeAllElements();
        txtHasil.setText("");
        txtKd.setText("");
        btnBatal.setEnabled(false);
        btnSimpan.setEnabled(false);
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        ModelProses mh = new ModelProses();
        String a = txtKd.getText();
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        String tgl = df.format(Calendar.getInstance().getTime());
        if (!a.equals("")) {
            String data[] = {id, txtKd.getText(), tgl,
                String.valueOf(alpha), String.valueOf(hasil_mse), String.valueOf(Math.round(hasil))
            };
            if (mh.insert(data) > 0) {
                JOptionPane.showMessageDialog(null, "Data Masuk");
                txtHasil.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Gagal");
            }
            btnBatal.setEnabled(false);
            btnSimpan.setEnabled(false);
            model.getDataVector().removeAllElements();
            model2.getDataVector().removeAllElements();
            txtKd.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Inputkan semua data barang", "Notifikasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void periodeAwalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_periodeAwalPropertyChange
        // TODO add your handling code here:
        if (periodeAwal.getDate() != null && periodeAkhir.getDate() != null) {
            SimpleDateFormat Format = new SimpleDateFormat("yyyy-MM-dd");
            dari = Format.format(periodeAwal.getDate());
            sampai = Format.format(periodeAkhir.getDate());
            System.out.println(dari);
            System.out.println(sampai);
        }
    }//GEN-LAST:event_periodeAwalPropertyChange

    private void periodeAkhirPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_periodeAkhirPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_periodeAkhirPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog FrmBarang;
    private usu.widget.ButtonGlass btnBatal;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnLihat;
    private usu.widget.ButtonGlass btnSimpan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private com.toedter.calendar.JDateChooser periodeAkhir;
    private com.toedter.calendar.JDateChooser periodeAwal;
    private javax.swing.JTable tblBarang;
    private javax.swing.JTable tblDataLampau;
    private javax.swing.JTextArea txtHasil;
    private javax.swing.JTextField txtKd;
    // End of variables declaration//GEN-END:variables
}
