/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spkdesi.view;

/**
 *
 * @author 6P52
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
    }

    public MenuUtama(String username) {
        initComponents();
        if (!username.equals("admin")) {
            menuUser.setEnabled(false);
            menuJenis.setEnabled(false);
            menuPemasok.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuJenis = new javax.swing.JMenuItem();
        menuPemasok = new javax.swing.JMenuItem();
        menuBeli = new javax.swing.JMenuItem();
        menuPersediaan = new javax.swing.JMenuItem();
        menuPakai = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuProses = new javax.swing.JMenuItem();
        menuPeramalan = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menuLaporan = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        menuUser = new javax.swing.JMenuItem();
        menuLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem Prediksi Pengadaan Bahan Bangunan Pada Toko Jaya Indah Bangunan Tanjung Pinang");

        jDesktopPane1.setOpaque(false);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );

        jMenuBar1.setBorder(null);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spkdesi/icon/dasher.png"))); // NOI18N
        jMenu1.setText("Master");
        jMenu1.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jMenu1.add(jSeparator1);

        menuJenis.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuJenis.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        menuJenis.setText("Kategori Barang");
        menuJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuJenisActionPerformed(evt);
            }
        });
        jMenu1.add(menuJenis);

        menuPemasok.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuPemasok.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        menuPemasok.setText("Pemasok");
        menuPemasok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPemasokActionPerformed(evt);
            }
        });
        jMenu1.add(menuPemasok);

        menuBeli.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuBeli.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        menuBeli.setText("Beli Barang");
        menuBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBeliActionPerformed(evt);
            }
        });
        jMenu1.add(menuBeli);

        menuPersediaan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuPersediaan.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        menuPersediaan.setText("Persediaan Barang");
        menuPersediaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPersediaanActionPerformed(evt);
            }
        });
        jMenu1.add(menuPersediaan);

        menuPakai.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuPakai.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        menuPakai.setText("Pemakaian Barang");
        menuPakai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPakaiActionPerformed(evt);
            }
        });
        jMenu1.add(menuPakai);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spkdesi/icon/education-miscellaneous.png"))); // NOI18N
        jMenu2.setText("Peramalan");
        jMenu2.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jMenu2.add(jSeparator2);

        menuProses.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuProses.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        menuProses.setText("Proses Hitung");
        menuProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProsesActionPerformed(evt);
            }
        });
        jMenu2.add(menuProses);

        menuPeramalan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuPeramalan.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        menuPeramalan.setText("Hasil Peramalan");
        menuPeramalan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPeramalanActionPerformed(evt);
            }
        });
        jMenu2.add(menuPeramalan);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spkdesi/icon/kedit.png"))); // NOI18N
        jMenu3.setText("Laporan");
        jMenu3.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jMenu3.add(jSeparator3);

        menuLaporan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuLaporan.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        menuLaporan.setText("Cetak Laporan");
        menuLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLaporanActionPerformed(evt);
            }
        });
        jMenu3.add(menuLaporan);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spkdesi/icon/kgpg-3.png"))); // NOI18N
        jMenu4.setText("Admin");
        jMenu4.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jMenu4.add(jSeparator4);

        menuUser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuUser.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        menuUser.setText("Tambah User");
        menuUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUserActionPerformed(evt);
            }
        });
        jMenu4.add(menuUser);

        menuLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuLogout.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        menuLogout.setText("Logout");
        menuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogoutActionPerformed(evt);
            }
        });
        jMenu4.add(menuLogout);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(766, 588));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuJenisActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        FrmKategori fj = new FrmKategori();
        fj.setTitle("JENIS BARANG");
        fj.setVisible(true);
        jDesktopPane1.add(fj);
    }//GEN-LAST:event_menuJenisActionPerformed

    private void menuPersediaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPersediaanActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        FrmPersediaan fp = new FrmPersediaan();
        fp.setTitle("PERSEDIAAN BARANG");
        fp.setVisible(true);
        jDesktopPane1.add(fp);
    }//GEN-LAST:event_menuPersediaanActionPerformed

    private void menuPakaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPakaiActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        FrmPakai fp = new FrmPakai();
        fp.setTitle("PEMAKAIAN BARANG");
        fp.setVisible(true);
        jDesktopPane1.add(fp);
    }//GEN-LAST:event_menuPakaiActionPerformed

    private void menuProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProsesActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        FrmProses fp = new FrmProses();
        fp.setTitle("PROSES HITUNG");
        fp.setVisible(true);
        jDesktopPane1.add(fp);
    }//GEN-LAST:event_menuProsesActionPerformed

    private void menuPeramalanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPeramalanActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        FrmPeramalan fp = new FrmPeramalan();
        fp.setTitle("HASIL PERAMALAN");
        fp.setVisible(true);
        jDesktopPane1.add(fp);
    }//GEN-LAST:event_menuPeramalanActionPerformed

    private void menuPemasokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPemasokActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        FrmPemasok fp = new FrmPemasok();
        fp.setTitle("KELOLA PEMASOK");
        fp.setVisible(true);
        jDesktopPane1.add(fp);
    }//GEN-LAST:event_menuPemasokActionPerformed

    private void menuBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBeliActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        FrmBeli fp = new FrmBeli();
        fp.setTitle("PEMBELIAN BARANG");
        fp.setVisible(true);
        jDesktopPane1.add(fp);
    }//GEN-LAST:event_menuBeliActionPerformed

    private void menuLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLaporanActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        FrmLaporan fp = new FrmLaporan();
        fp.setTitle("CETAK PERAMALAN");
        fp.setVisible(true);
        jDesktopPane1.add(fp);
    }//GEN-LAST:event_menuLaporanActionPerformed

    private void menuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogoutActionPerformed
        // TODO add your handling code here:
        dispose();
        FrmLogin Log = new FrmLogin();
        Log.setVisible(true);
    }//GEN-LAST:event_menuLogoutActionPerformed

    private void menuUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUserActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        FrmAdmin fa = new FrmAdmin();
        fa.setTitle("Tambahakan User");
        fa.setVisible(true);
        jDesktopPane1.add(fa);
    }//GEN-LAST:event_menuUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>      
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                MenuUtama mn = new MenuUtama();
                //mn.setExtendedState(MAXIMIZED_BOTH);
                mn.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenuItem menuBeli;
    private javax.swing.JMenuItem menuJenis;
    private javax.swing.JMenuItem menuLaporan;
    private javax.swing.JMenuItem menuLogout;
    private javax.swing.JMenuItem menuPakai;
    private javax.swing.JMenuItem menuPemasok;
    private javax.swing.JMenuItem menuPeramalan;
    private javax.swing.JMenuItem menuPersediaan;
    private javax.swing.JMenuItem menuProses;
    private javax.swing.JMenuItem menuUser;
    // End of variables declaration//GEN-END:variables
}
